- name: cart configuration
  hosts: cart
  become: yes
  tasks:
  - name: disables packages
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enables packages
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs packages
    ansible.builtin.package:
      name: nodejs
      state: present
      
  - name: create roboshop system cart
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system cart
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete cart file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent    

  - name: downlode code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip       

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: systemd service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: start and enable service
    ansible.builtin.service:
      name: cart
      enabled: yes
      state: started   
      daemon_reload: true