
[mongodb]
mongodb.chandrahasa.online

[redis]
redis.chandrahasa.online

[mysql]
mysql.chandrahasa.online

[rabbitmq]
rabbitmq.chandrahasa.online

[catalogue]
catalogue.chandrahasa.online

[cart]
cart.chandrahasa.online

[user]
user.chandrahasa.online

[shipping]
shipping.chandrahasa.online

[payment]
payment.chandrahasa.online

[frontend]
172.31.10.54
[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321



