
[mongodb]
mongodb.chandrahas.online

[redis]
redis.chandrahas.online

[mysql]
mysql.chandrahas.online

[rabbitmq]
rabbitmq.chandrahas.online

[catalogue]
catalogue.chandrahas.online

[cart]
cart.chandrahas.online

[user]
user.chandrahas.online

[shipping]
shipping.chandrahas.online

[payment]
payment.chandrahas.online

[frontend]
frontend.chandrahas.online



