
[mongodb]
mongodb.chandrahasa.online

[redis]
redis.chandrahasa.online

[mysql]
mysql.chandrahasa.online

[rabbitmq]
rabbitmq.chandrahasa.online

[catalogue]
catalogue.chandrahasa.online

[cart]
cart.chandrahasa.online

[user]
user.chandrahasa.online

[shipping]
shipping.chandrahasa.online

[payment]
payment.chandrahasa.online

[frontend]
frontend.chandrahasa.online



